name: flutter_mvvm
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0


dependencies:
  flutter:
    sdk: flutter
    
  flutter_localizations:
    sdk: flutter    

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  material_design_icons_flutter: ^7.0.7296
  google_fonts: ^6.2.1
  go_router: ^15.1.2
  flutter_native_splash: ^2.4.6
  # flutter_launcher_icons: ^0.14.3
  dio: ^5.8.0+1

flutter_native_splash:
  color: "#ffffff"
  image: assets/app/android_ios.png
  # branding: assets/app/android_ios.png
  # branding_bottom_padding: 24
  color_dark: "#ffffff"
  image_dark: assets/app/android_ios.png
  branding_dark: assets/app/android_ios.png

  android_12:
    image: assets/app/android_ios.png
    icon_background_color: "#ffffff"
    image_dark: assets/app/android_ios.png
    icon_background_color_dark: "#ffffff"

  web: false
  android: true
  ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
